apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: aqua-web
  name: aqua-web
  namespace: aqua-security
spec:
  port:
    targetPort: aqua-web
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aqua-web
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: aqua-web
  labels:
    app: aqua-web
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: aqua-web-ssl
    - nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
      name: aqua-web
  selector:
    app: aqua-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqua-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-web
  template:
    metadata:
      labels:
        app: aqua-web
      name: aqua-web
    spec:
      serviceAccount: aqua-account
      imagePullSecrets:
        - name: aqua-registry
      containers:
        - name: aqua-web
          image: registry.aquasec.com/console:4.6
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: SCALOCK_DBUSER
              value: "postgres"
            - name: SCALOCK_DBPASSWORD
              valueFrom:
                      secretKeyRef:
                              name: aqua-database-password
                              key: db-password
            - name: SCALOCK_DBNAME
              value: "scalock"
            - name: SCALOCK_DBHOST
              value: aqua-db
            - name: SCALOCK_DBPORT
              value: "5432"
            - name: SCALOCK_AUDIT_DBUSER
              value: "postgres"
            - name: SCALOCK_AUDIT_DBPASSWORD
              valueFrom:
                      secretKeyRef:
                              name: aqua-database-password
                              key: db-password
            - name: SCALOCK_AUDIT_DBNAME
              value: "slk_audit"
            - name: SCALOCK_AUDIT_DBHOST
              value: aqua-db
            - name: SCALOCK_AUDIT_DBPORT
              value: "5432"
            - name: AQUA_DOCKERLESS_SCANNING
              value: "1"
            - name: AQUA_GRPC_MODE
              value: "1"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket-mount
          ports:
            - containerPort: 8080
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
